# Copyright 2019, Advanced UniByte GmbH.
# Author Marie Lohbeck.
#
# This file is part of Gafaspot.
#
# Gafaspot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Gafaspot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Gafaspot.  If not, see <https://www.gnu.org/licenses/>.




# example config
# copy this file to gafaspot_config.yaml and adapt it.
# For further explanations, see doc/config_explanation.md




#######################################
#
# general config for gafaspot
#######################################

webservice-address: 127.0.0.1:8080

# maximum values for new reservations
max-reservation-duration-days: 30
max-queuing-time-months: 2




######################################
#
# config concerning database
######################################

# file path of Gafaspot's SQLite database
db-path: ./gafaspot.db

# ttl for 'delete_on' columns in database
database-ttl-months: 12




######################################
#
# config concerning Vault
######################################

vault-address: http://127.0.0.1:8200/v1

# credentials for AppRole Auth Method
approle-roleID: someID
approle-secretID: someSecret

# policy name belonging to LDAP Auth Method
ldap-group-policy: gafaspot-user-ldap




# define composition of environments through secrets engines
environments:

  demo0:
    show-name: DEMO 0
    description: "Some description for DEMO 0;
                  can use multiple lines and
                  HTML tags <br> for formatting."

    secrets-engines:
    - name: NetApp
      type: ontap
      role: gafaspot
      
    - name: ActiveDirectory
      type: ad
      role: gafaspot
      
    - name: SSH
      type: ssh
      role: gafaspot
    
  demo1:
    show-name: DEMO 1
    secrets-engines:
    - name: NetApp
      type: ontap
      role: gafaspot
      
    - name: someDatabase
      type: database
      role: gafaspot
      
    - name: otherDatabase
      type: database
      role: gafaspot
  
  demo2:
    show-name: DEMO 2
    description: this is demo environment 2
    secrets-engines:
      - name: SSH
        type: ssh
        role: gafaspot

      - name: MySQL
        type: database
        role: gafaspot