
# example config

db-path: ./gafaspot.db

vault-address: http://127.0.0.1:8200/v1
webservice-address: 127.0.0.1:8080

approle-roleID: someID
approle-secretID: someSecret

ldap-group-policy: gafaspot-users

environments:

  demo0:
    show-name: DEMO 0
    description: this is demo environment 0

    secret-engines:
    - name: NetApp
      type: ontap
      role: gafaspot
      
    - name: ActiveDirectory
      type: ad
      role: gafaspot
    
  demo1:
    show-name: DEMO 1
  
    secret-engines:
    - name: NetApp
      type: ontap
      role: gafaspot
      
    - name: someDatabase
      type: database
      role: gafaspot
      
    - name: otherDatabase
      type: database
      role: gafaspot